### ISSUE TITLE
what is the meaning that tdna_st or tdna_end is "-"

### ISSUE THREAD

**Issue by BioLaoXu** [noble-research-institute/TDNAscan#3]
Hi dear team 
TDNAscan is a powerful tools for detect T-DNA insert position,i have tested TDNAscan can detect the result ,but others tools can not detect any results(like: transgeneR),but the detected results show that   tdna_st or tdna_end is "-",so i want to know what is the meaning,my results just like this :
![图片](https://user-images.githubusercontent.com/13416926/81245472-a1cf0c00-9047-11ea-9e17-bc45eb23fc2e.png)

**Comment by yinbingge** [comment]
This is because there are only informative reads from only one side of the TDNA insertion. We can not detect how the TDNA was truncated on one side of the tdna insertion . This happens sometimes. You may notice that we also identified three confirmed insertions with “-“ positions in case study 2 of our paper. You can use frequency and CLR values to decide how confident these identified TDNA insertions are. The higher of those values, the more likely those insertions are real. Good luck, 
Liang
